### ISSUE TITLE
No information window shown using neovim

### ISSUE THREAD

**Issue by jkunlin** [rhysd/vim-grammarous#39]
After using ":GrammarousCheck" command, it highlights the errors.
But there is not information window when I move cursor on the locations.

**Comment by rhysd** [comment]
Let me confirm one thing. After errors are highlighted, does moving cursor to the highlighted area open information window?

**Comment by jkunlin** [comment]
Sometimes It will and sometimes will not.

For example, if I select one line from head to tail in visual mode, and run ":GrammarousCheck", then moving cursor to the highlighted area doesn't open information window.
But when I select this line from tail to head, and run the command again, the information window will be shown.

**Comment by befedo** [comment]
Got the same issue. While I now know that selecting from tail to head is a little workaround.

**Comment by rhysd** [comment]
I noticed that this is current expected behavior. To see the first error, we need to jump the cursor to first error position.

However, I agree that showing information window automatically is also useful. I think adding a new variable to control the behavior is a good way to do that.

**Comment by rhysd** [comment]
I implemented the feature in f02ce8e. Please try the latest with below config:

```vim
let g:grammarous#show_first_error = 1
```

Default value of the variable is `0` because of compatibility.

**Comment by RonanMacF** [comment]
Hi, has there been any progress on this issue? I am experiencing it myself using neovim v.05.

**Comment by domi-eck** [comment]
This issue still exists. The proposed fix doesn't help. The curser moves to the first error, but the information windows still doesn't show up.
